version: '3.8'
services:
  db:
    image: postgres:14
    container_name: subscriptiondb
    environment:
      POSTGRES_DB: subscriptionsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit:
    image: rabbitmq:3-management
    container_name: subscriptionrabbit
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  subscription-service:
    build: .
    container_name: subscriptionservice
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    ports:
      - "8080:8080"
